In [1]:
1+2

3

In [2]:
1-2

-1

In [3]:
4*5

20

In [4]:
7/5

1.4

In [5]:
3 ** 2

9

In [6]:
type(10)

int

In [7]:
type(2.718)

float

In [8]:
type("hello")

str

In [9]:
x=10
print(x)

10


In [10]:
x=100
print(x)

100


In [11]:
y=3.14
x*y

314.0

In [12]:
type(x*y)

float

In [13]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [14]:
len(a)

5

In [15]:
a[0]

1

In [16]:
a[4]

5

In [17]:
a[4]=99
print(a)

[1, 2, 3, 4, 99]


In [18]:
print(a)

[1, 2, 3, 4, 99]


In [19]:
a[0:2]

[1, 2]

In [20]:
a[1:]

[2, 3, 4, 99]

In [21]:
a[:3]

[1, 2, 3]

In [22]:
a[:-1]

[1, 2, 3, 4]

In [23]:
a[:-2]

[1, 2, 3]

In [24]:
me={'height':100}
me['height']

100

In [25]:
me['weight']=70
print(me)

{'height': 100, 'weight': 70}


In [1]:
hungry=True
sleepy=False
type(hungry)

bool

In [2]:
not hungry

False

In [3]:
hungry and sleepy

False

In [4]:
hungry or sleepy

True

In [5]:
hungry = True
if hungry:
    print("I'm hungry")

I'm hungry


In [8]:
hungry = False
if hungry:
    print("I'm hungry")
else:
    print("I'm not hungry")
    print("I'm sleepy")

I'm not hungry
I'm sleepy


In [9]:
for i in [1,2,3]:
    print(i)

1
2
3


In [11]:
def hello():
    print("Hello World!")
    
hello()

Hello World!


In [13]:
def hello(object):
    print("Hello " + object + "!")
    
hello("cat")

Hello cat!


In [14]:
# coding: utf-8
class Man:
    """サンプルクラス"""

    def __init__(self, name):
        self.name = name
        print("Initilized!")

    def hello(self):
        print("Hello " + self.name + "!")

    def goodbye(self):
        print("Good-bye " + self.name + "!")

m = Man("David")
m.hello()
m.goodbye()

Initilized!
Hello David!
Good-bye David!


In [1]:
import numpy as np
x = np.array([1.0,2.0,3.0])
print(x)

[1. 2. 3.]


In [2]:
type(x)

numpy.ndarray

In [3]:
x = np.array([1.0,2.0,3.0])
y = np.array([2.0,4.0,6.0])
x+y

array([3., 6., 9.])

In [4]:
x-y

array([-1., -2., -3.])

In [5]:
x/y

array([0.5, 0.5, 0.5])

In [6]:
x/2.0

array([0.5, 1. , 1.5])

In [7]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [8]:
A.shape

(2, 2)

In [9]:
A.dtype

dtype('int64')

In [10]:
B = np.array([[3,0],[0,6]])
A+B

array([[ 4,  2],
       [ 3, 10]])

In [11]:
A*B

array([[ 3,  0],
       [ 0, 24]])

In [12]:
print(A)

[[1 2]
 [3 4]]


In [13]:
A*10

array([[10, 20],
       [30, 40]])

In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([10,20])
A*B

array([[10, 40],
       [30, 80]])

In [15]:
X = np.array([[51,55],[14,19],[0,4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [16]:
X[0]

array([51, 55])

In [17]:
X[0][1]

55

In [18]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [20]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [23]:
X[np.array([0,2,4])]

array([51, 14,  0])

In [24]:
X>15

array([ True,  True, False,  True, False, False])

In [26]:
X[X>15]

array([51, 55, 19])